# 激活的环境
spring:
  profiles:
    active: dev
  config:
    import: classpath:project.yml
    encoding: UTF-8
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false

# URL 白名单
security:
  permit-urls:
    - /auth/**
    - /swagger-ui/**
    - /swagger-ui.html
    - /v3/api-docs/**
    - /enums/**
    - /user/register

# JWT 配置
jwt:
  secret: xusheng-secret-key-please-change-to-strong-key
  expire-days: 1
  default-role: ROLE_USER